### ISSUE TITLE
Crashed when WpfGame is hosted it tabitem in WPF

### ISSUE THREAD

**Issue by msmshazan** [MarcStan/MonoGame.Framework.WpfInterop#14] opened 2019-01-04 09:55 UTC
![image](https://user-images.githubusercontent.com/20334207/50682408-c28ee800-1034-11e9-8f17-f9ef994b99c5.png)

I think the cause in this line. https://github.com/MarcStan/MonoGame.Framework.WpfInterop/blob/master/MonoGame.Framework.WpfInterop/D3D11Host.cs#L309

**Comment by msmshazan** [comment] 2019-01-04 14:20
It's an integrated GPU. (Intel HD 620 )
Here's the dxdiag dump 
[DxDiag.txt](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/files/2727283/DxDiag.txt)

**Comment by msmshazan** [comment] 2019-01-04 14:21
Also the program crashes only when closing

**Comment by msmshazan** [comment] 2019-01-04 14:33
Here's the gif showing the issue
![2019-01-04_20-02-39](https://user-images.githubusercontent.com/20334207/50693031-cda93e80-105b-11e9-855d-2fec9d168e46.gif)

**Comment by MarcStan** [comment] 2019-01-05 13:32
Dxdiag looks good (supports DirectX 12).

I saw that you uploaded your project to github as well but I can't reproduce due to a few missing files (CustomInterTabClient.cs, GraphicsContext.cs and ChildWindow.xaml(.cs) are not checked in).

So far I was also not able to reproduce with my own samples. Can you provide me with a full project (e.g. upload the missing files)?

**Comment by msmshazan** [comment] 2019-01-05 16:35
Done sorry about that my mistake

**Comment by msmshazan** [comment] 2019-01-05 18:51
I updated the repo https://github.com/msmshazan/ShaderEdit/commit/485c30eb8e10a3e0d97aa7a69d6d527337f530f4

**Comment by MarcStan** [comment] 2019-01-06 13:18
Unfortunately I am unable to reproduce this crash (I tried with both an integrated Intel HD 620 and a dedicated GPU). When I close the shader editor it just exits without throwing an exception.

You explicitely stated in the title that the crash happens when the WpfGame control is inside a tab item. Does that mean it doesn't crash for you when it is hosted outside of a tab item (e.g. directly in the window)?

Here's a few more ideas that come to mind that you could test:

1. See if you can reproduce the crash with my WpfTest application. You might have to replace the StartupUri in [App.xaml](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/blob/master/WpfTest/App.xaml) with one of the tab controls (e.g. "Views/TabWindow.xaml"). For me it never crashes when I close it, no matter which view I set as startup.

2. Maybe a driver issue? Are you on the latest driver for your GPU?

3. Set WpfGame.UseASingleSharedGraphicsDevice = true in App.xaml.cs (must happen before the first WpfGame is loaded), though I doubt this will help since the crash occurs on exit.

4. I noticed you are using nuget package ModernChrome 1.0.0-alpha001 which appears quite unmaintained. Can you (temporarily) try to run your editor without this nuget (just the default styling). Maybe it's hooking into the closing event and doing something (long shot, since it didn't crash for me..)

Sorry that I can't help further right now (since I can't reproduce).

**Comment by msmshazan** [comment] 2019-01-07 08:51
It seems that your WpfTest application is throwing an exception while disposing / closing the window . I included the gif below showing the issue. 
![2019-01-07_14-19-02](https://user-images.githubusercontent.com/20334207/50758181-78517500-1287-11e9-9ed8-3774d2eb3816.gif)

**Comment by MarcStan** [comment] 2019-01-08 19:05
So I was finally able to reproduce by going to Debug -> Windows -> Exception Settings and checking "Common Language Runtime Exceptions" (especially the first point in the list "all exceptions not in this list".

I see the exception now but I can simply press F5 to continue without it having any negative effect.

Infact when you run either WpfTest or ShaderEdit without a debugger you will not notice anything (e.g. Event Viewer will not show a crash).

So if you simply uncheck "<All Common Language Runtime Exceptions not in this list>" in the exception settings you will no longer see it.

I don't have too much time right now but I guess the real fix would be to fix the issue in MonoGame that causes me to need the workaround in the first place and then wait for the next MonoGame release.

I'll leave this issue open for now.

**Comment by MarcStan** [comment] 2019-01-09 17:52
I did a bit more research and found that the [crash happens here](https://github.com/MonoGame/MonoGame/blob/6ef30f19b936b07fc6598e0c3837c6aa4db2bca0/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L842-L847).

As you can see the exception is caught directly as some platforms don't support SwapChain.ContainingOutput (WPF being one of them).

This is the remark of SwapChain.ContainingOutput:

``` xml
// If the method succeeds, the output interface will be filled and its reference
// count incremented. When you are finished with it, be sure to release the interface
// to avoid a memory leak.The output is also owned by the adapter on which the swap
// chain's device was created.You cannot call GetContainingOutput on a swap chain
// that you created with SharpDX.DXGI.Factory2.CreateSwapChainForComposition(SharpDX.ComObject,SharpDX.DXGI.SwapChainDescription1@,SharpDX.DXGI.Output,SharpDX.DXGI.SwapChain1).
```
So I'll close this issue now as the exception in MonoGame is "by design" and also doesn't negatively impact the application runtime (no memory leak or similar as I initially feared).

**Closed by MarcStan** 2019-01-09 17:52 UTC
Labels: bug
