### ISSUE TITLE
I have a problem, please help me.

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#16] opened 2019-03-06 15:13 UTC
I created a wpf project and created two classes that inherit WpfGame. I asked them to draw a picture as well. I ran perfectly on one of my computers and showed what I wanted, but the same The code is having problems on another computer.

![image](https://user-images.githubusercontent.com/18465053/53891257-f69e7d80-4064-11e9-9fa1-b5a6ac3d2aaf.png)

This is my first wpfGame window

![image](https://user-images.githubusercontent.com/18465053/53891301-0fa72e80-4065-11e9-8805-2d65aaabc089.png)

This is my second wpfGame window。
The second window should have a picture, but it doesn't show up, only shows my grid.But the code for these two windows is the same。

Finally, I am on the same computer, the same code, this second window shows the picture is normal。

**Comment by esengine** [comment] 2019-03-06 15:14
I think maybe my graphics card problem, my display is normal integrated graphics, the display is not normal is 1080Ti discrete graphics

**Comment by esengine** [comment] 2019-03-06 15:15
Have you encountered this situation, I can't know what the bug is, because it doesn't have any error, just lost the texture.

**Comment by esengine** [comment] 2019-03-06 15:17
![image](https://user-images.githubusercontent.com/18465053/53891724-ef2ba400-4065-11e9-8028-0549659857ce.png)

And I am pretty sure that my drawing code still works on a computer that I am not displaying properly, and has information about the image.

**Comment by MarcStan** [comment] 2019-03-06 18:43
No I haven't encountered such an issue before.

Are you using custom rendertargets or Draw calls with [custom sort modes](https://docs.microsoft.com/en-us/previous-versions/windows/xna/bb199041(v%3dxnagamestudio.10))?

**Comment by esengine** [comment] 2019-03-07 02:13
I did not use a custom renderTarget. sortMode I chose immediate

**Comment by MarcStan** [comment] 2019-03-07 19:12
Could be from different monogame/driver/etc. versions installed on both PCs then..

Also have you tried the normal SortMode (Deferred)?

**Comment by esengine** [comment] 2019-03-08 02:34
I have tried it, I am going to reinstall the computer today, and then try again.

**Comment by esengine** [comment] 2019-03-09 04:33
![image](https://user-images.githubusercontent.com/18465053/54066209-4fd5ff00-4267-11e9-8e0a-4be506b766da.png)

I have failed to reinstall the computer. Have you seen these dotted lines? This is the line I drawn. It is not complete. I also marked a place with a red rectangle. There is originally a picture, but you Look carefully at this location, you will find something faint, but not complete

**Comment by esengine** [comment] 2019-03-09 04:37
And there is a new problem, I don't know if I should open a new issue?

When I zoomed in/out the window, it showed an error.

> SharpDX.SharpDXException: "HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been paused. Use GetDeviceRemovedReason to determine the appropriate action.

**Comment by MarcStan** [comment] 2019-03-09 11:26
3 questions from my side:

1. What display resolution are you using and what default scale is it set to? (A lot of high resolution displays will default to 125-200% on Windows 10). There was an existing issue over on [gitlab](https://gitlab.com/MarcStan/MonoGame.Framework.WpfInterop/issues/17) that I solved with version 1.7.
2. Can you share a sample project that I could use to verify?
3. If one isn't the case, how are you zooming into the window? Are you using the windows magnifier or something else?

**Comment by esengine** [comment] 2019-03-09 11:36
1.  i use dual display， both are 1920 * 1080 resolution
2. i don't know if i can make a successful example to you, but i am willing to do this example. i will try to give you an example before Monday.
3. i just use it to simply zoomed out and zoomed in. like the picture i sent below.

![image](https://user-images.githubusercontent.com/18465053/54071014-5cc41400-42a2-11e9-8a3a-3a96b3ff3fc2.png)

**Comment by esengine** [comment] 2019-03-11 13:59
https://github.com/esengine/WpfInterop.Test

I built a new project to test it. Sorry, I didn't find any problems. Maybe there are other operations in my project. I will continue to check it. I will close this question until I find the source of the problem. I will reopen it again.

**Comment by esengine** [comment] 2019-03-14 14:01
I redisconvered the problem and found this problem when you open the second window.

https://github.com/esengine/WpfInterop.Test

**Comment by MarcStan** [comment] 2019-03-18 19:16
Unfortunately I can't reproduce (neither with a GPU nor with integrated graphics), it always renders correctly.

However on the (weak) integrated GPU I noticed quite high usage and a bit of lag.
Looking at your code, I saw that the Draw\*Grid methods both iterate width*height and essentially draw the same line over and over.
`DrawHorizontalGrid` only needs to interate `height` and `DrawVerticalGrid` only needs to interate `width`.

By dropping one loop for each the performance improved quite a lot.

``` csharp
private void DrawHorizontalGrid(decimal width, decimal height, decimal maxWidth, decimal maxHeight,
            Vector2 transform)
{
  // this is not needed and causes performance issues -> for (var i = maxWidth - width; i < maxWidth; i++)
  for (var j = maxHeight - height; j < maxHeight; j++)
    spriteBatch.DrawLine(camera.Position.X,
      float.Parse((gridSize * j).ToString(CultureInfo.InvariantCulture)), transform.X,
      float.Parse((gridSize * j).ToString(CultureInfo.InvariantCulture)),
      Color.Green, 1f);
}
```

**Comment by esengine** [comment] 2019-03-19 07:08
Thank you for your optimization suggestions. After I checked it out, I found that it worked abnormally with the dockpanel in Extended.Wpf.Toolkit, but it only appeared on my other high-profile computer. The problem. My current practice is to use only one main window to host your wpfgame, although it is very troublesome, but got a relief.

**Comment by MarcStan** [comment] 2019-03-19 16:13
Can you try to this:

``` csharp
D3D11Host.UseASingleSharedGraphicsDevice = true;
```

You have to call it **once before any game windows are created** (e.g. App.xaml.cs constructor).

I changed the default behaviour in 1.7 to false (true will enable the legacy behaviour).

**Comment by MarcStan** [comment] 2019-03-24 19:07
Closing this as I was able to test this with a dedicated GPU and I had the same glitch and it was fixed by the code above.

Feel free to reopen, if it doesn't work for you.

**Closed by MarcStan** 2019-03-24 19:07 UTC
